server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    locations:
      classpath: db/migration
    baseline-on-migration: true

  jpa:
    open-in-view: false